AWSTemplateFormatVersion: '2010-09-09'


Parameters:
  GithubToken:
    Type: String
    Description: access token to github
    Default: xxxx # should be read from the main stack template parameter
  CloudmrServer:
    Type: String
    Description: "CLOUDMR_SERVER"
  TessServer:
    Type: String
    Description: "TESS_SERVER"
  ProfileServer:
    Type: String
    Description: "PROFILE_SERVER"
  ApiUrl:
    Type: String
    Description: "API_URL"
  ApiToken:
    Type: String
    Description: "API_TOKEN"



Resources:
  AmplifyConsoleServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - amplify.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: AmplifyConsoleServicePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'codebuild:StartBuild'
                  - 'codebuild:BatchGetBuilds'
                Resource: '*'
  TESSFrontend:
    Type: AWS::Amplify::App
    Properties:
      AccessToken: !Ref GithubToken
      AutoBranchCreationConfig:
        EnableAutoBranchCreation: true
        EnableAutoBuild: true
        AutoBranchCreationPatterns:
          - "stable"
          - "dev"
      CustomRules:
        - Source: "/websignin/"
          Status: "200"
          Target: "/index.html"
        - Source: "</^[^.]+$|\\.(?!(css|gif|ico|jpg|jpeg|js|png|txt|svg|woff|woff2|ttf|map|json|webp)$)([^.]+$)/>"
          Status: "200"
          Target: "/index.html"
      Description: "Your App Description Here"
      EnableBranchAutoDeletion: false
      EnvironmentVariables:
        - Name: "CLOUDMR_SERVER"
          Value: !Ref CloudmrServer
        - Name: "TESS_SERVER"
          Value: !Ref TessServer
        - Name: "PROFILE_SERVER"
          Value: !Ref ProfileServer
        - Name: "API_URL"
          Value: !Ref ApiUrl # REQUEST, POST {"type": (array or string)["mr optimum","upload",'tess'],"token":""}, RESULTS {"api-token":"dedddd"} you want to check if if the results
        - Name: "API_TOKEN"
          Value: !Ref ApiToken
      Name: "TESS"
      Platform: "WEB"
      Repository: "https://github.com/cloudmrhub-com/TESS-frontend"
      Tags:
        - Key: "owner"
          Value: "cloudmrhub"
        - Key: "maintainer"
          Value: "YL6709"
        - Key: "project"
          Value: "tess-v1"
        - Key: "team"
          Value: "cloudmrhub"
        - Key: "status"
          Value: "prod"
        - Key: "deletable"
          Value: "check"


  StableBranch:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: !GetAtt TESSFrontend.AppId
      BranchName: "stable"
      EnableAutoBuild: true
      EnablePullRequestPreview: true

      BuildSpec: |
        version: 1
        frontend:
          phases:
            preBuild:
              commands:
                - yarn install
            build:
              commands:
                - cat << EOF > src/env.ts
                - export const CLOUDMR_SERVER = '$CLOUDMR_SERVER';
                - export const TESS_SERVER = '$TESS_SERVER';
                - export const PROFILE_SERVER = '$PROFILE_SERVER';
                - export const API_TOKEN = '$API_TOKEN';
                - export const API_URL = '$API_URL';
                - EOF
                - yarn build
          artifacts:
            baseDirectory: build
            files:
              - '**/*'
          cache:
            paths:
              - node_modules/**/*
      Framework: "WEB"
      Stage: "PRODUCTION"

  DevBranch:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: !GetAtt TESSFrontend.AppId
      BranchName: "dev"
      EnableAutoBuild: true
      EnablePullRequestPreview: false
      # Omit API loading for dev branch to allow testing of new server rotues
      Framework: "WEB"

Outputs:
  AmplifyAppDomain:
    Value: !Sub "${StableBranch.BranchName}.${TESSFrontend.DefaultDomain}"
    Description: "Amplify App Domain"
    Export:
      Name: "AmplifyAppDomain"

  AmplifyAppId:
    Value: !GetAtt TESSFrontend.AppId
    Description: "Amplify App Id"
    Export:
      Name: "AmplifyAppId"